version: '3.8'

services:
  ## database
  mysql:
    image: mysql:latest
    container_name: project_name-db
    environment:
      MYSQL_ROOT_PASSWORD: rootPW
      MYSQL_DATABASE: project_name
      MYSQL_USER: project_name
      MYSQL_PASSWORD: project_name
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: project_name-redis
    ports:
      - "6379:6379"
    networks:
      - backend

  ## monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: project_name-prometheus
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus-config.yaml'
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-network

  loki:
    image: grafana/loki:latest
    container_name: project_name-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: project_name-grafana
    #    set in instance
    #    environment:
    #      - GF_SECURITY_ADMIN_USER=local
    #      - GF_SECURITY_ADMIN_PASSWORD=local
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring-network

networks:
  backend:
    driver: bridge
  monitoring-network:
    driver: bridge

volumes:
  mysql_data:
  loki_data: