CREATE DATABASE IF NOT EXISTS PROJECT_NAME;
CREATE DATABASE IF NOT EXISTS TESTDB;

-- CREATE USER IF NOT EXISTS 'project_name'@'%' IDENTIFIED BY 'project_name';
--
-- GRANT ALL PRIVILEGES ON PROJECT_NAME.* TO 'project_name'@'%';
GRANT ALL PRIVILEGES ON TESTDB.* TO 'project_name'@'%';

FLUSH PRIVILEGES;