apiVersion: 1

deleteDatasources:
  - name: prometheus
  - name: loki

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    editable: true

  - name: loki
    uid: loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    isDefault: false
    editable: true

  - name: tloki
    uid: tloki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    isDefault: false
    editable: true